[package]
name = "rest-api-shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my-http-server = { branch = "0.2.4", git = "https://github.com/MyJetTools/my-http-server.git" }
my-http-server-controllers = { branch = "0.2.4", git = "https://github.com/MyJetTools/my-http-server-controllers.git" }
rust-extensions = { branch = "0.1.0", git = "https://github.com/MyJetTools/rust-extensions.git" }
my-http-server-swagger = { branch = "0.2.4", git = "https://github.com/MyJetTools/my-http-server-swagger.git" }


async-trait = "*"
tonic = { version = "*", features = ["tls", "tls-roots", "prost"] }
anyhow = "*"
tokio = { version = "*", features = ["full"] }
hyper = { version = "*", features = ["full"] }
prost = "*"
serde = { version = "*", features = ["derive"] }
tokio-util = "*"
futures = "*"
signal-hook = "*"
prost-types = "*"
enc_file = "*"
base64 = "*"
